apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3
  template:
    metadata:
      labels:
        app: s3
    spec:
      containers:
      - name: s3
        image: 192.168.56.10:5000/s3-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "400m"
            memory: "500Mi"
      schedulerName: rl-scheduler

---

apiVersion: v1
kind: Service
metadata:
  name: s3-external
  namespace: openfaas-fn
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: s3
