apiVersion: apps/v1
kind: Deployment
metadata:
  name: float-operations
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: float-operations
  template:
    metadata:
      labels:
        app: float-operations
    spec:
      containers:
      - name: float-operations
        image: 192.168.56.10:5000/float-operations-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "400m"
            memory: "250Mi"
      schedulerName: rl-scheduler

---

apiVersion: v1
kind: Service
metadata:
  name: float-operations-external
  namespace: openfaas-fn
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: float-operations

