apiVersion: apps/v1
kind: Deployment
metadata:
  name: linpack
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linpack
  template:
    metadata:
      labels:
        app: linpack
    spec:
      containers:
      - name: linpack
        image: 192.168.56.10:5000/linpack-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "400m"
            memory: "256Mi"
      schedulerName: rl-scheduler

---

apiVersion: v1
kind: Service
metadata:
  name: linpack-external
  namespace: openfaas-fn
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: linpack
